[project]
name = "dasktest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bokeh>=3.7.2",
    "dask>=2025.4.1",
    "dask-jobqueue>=0.9.0",
    "distributed>=2025.4.1",
    "jupyterlab>=4.4.1",
]
